"""Content for the build book: decisions, component breakdown, laundry comparison, walkthrough list."""

DECISIONS = [
    ("Coach length", "Used East to West's 26 ft. One review quotes 24 ft; the manufacturer page wins."),
    ("Body width", "East to West does not publish it. Modelled at 91 in, the same figure used earlier in this thread. ESTIMATE."),
    ("Front overhang", "Modelled at 40 in from the Transit cab shape, which puts the rear overhang at 94 in. ESTIMATE."),
    ("Floor and roof heights", "Floor 36 in above ground and roof 121 in, so 81 in interior height (confirmed) and 137 in overall with the AC (confirmed) both hold."),
    ("Rear wheels", "Modelled as dual rear wheels, implied by the 7,275 lb rear axle rating. ESTIMATE."),
    ("Floorplan positions", "No dimensioned floorplan is published. The order of rooms follows East to West and dealer descriptions; exact cabinet positions are modelled. ESTIMATE."),
    ("Entry door", "Curbside, behind the cab, opening into the dinette area. ESTIMATE."),
    ("AC position", "The Chill Cube stays in the existing 14x14 opening, modelled mid-roof at 130 in from the rear wall. Panels split into a rear group of 3 and a front group of 3 around it. ESTIMATE until the opening is measured."),
    ("Panel orientation", "All six panels run crosswise (68.35 in across the roof) because roof length is the scarce dimension."),
    ("Roof vents", "The bath fan, galley fan, cabover fan and shower skylight end up under panels. Modelled with low-profile covers on taller Z-brackets (2.5 in clearance). Swap any tall dome cover for a low-profile one."),
    ("Starlink", "You said Starlink, not which dish. Modelled the Starlink Mini on a flat mount beside the AC: 40-50 W typical against 75-100 W for the Standard, and it fits the side margin. The Standard (23.4 x 13.4 in) would also fit there."),
    ("Combiner", "One roof combiner between the rear panel group and the AC, feeding PV1 and PV2 as two trunk runs down a rear-corner chase."),
    ("RV5 location", "Inside the roadside desk pedestal, on the side wall, directly above the battery box. Keeps the kneehole open and the 48V run to the packs short."),
    ("Battery box position", "Centred 30 in from the rear wall (64 in behind the rear axle), between the spare tire and the hitch, hung from the frame rails with its bottom 12 in above ground. ESTIMATE."),
    ("Spare tire", "Kept in place under the frame, ahead of the battery box."),
    ("Exhaust", "Routed to exit curbside ahead of the battery box so the box is not in the exhaust stream."),
    ("Orion-Tr chargers", "Under the passenger seat near the starter battery: a short 12V lead, then one 48V run back along the curbside frame rail. Lower current over the long run than placing them at the tail."),
    ("Generator tie-in", "Generator and shore power meet at a transfer switch under the curbside bench, then one 120V run under the floor to the RV5 AC input. Run the RV5 in Standard or Silent charge mode on the generator."),
    ("Laundry A", "Bath side, between the bath wall and the fridge, replacing the drawer stack. Fridge moved one slot forward in the model to make the adjacency work. ESTIMATE."),
    ("Laundry B", "Rear garage, curbside rear corner under the lift bed, vented through the rear wall. The load hatch is modelled on the curbside wall ahead of it."),
    ("Lift bed", "Shown raised (office mode) in every render. Lowered underside modelled at 38 in above the floor. ESTIMATE."),
    ("Tail lamps", "Rendered as smoked lenses so no red tones appear anywhere; the real coach keeps its legal red lamps."),
    ("Tow car", "Generic small hatch built to Abarth dimensions (144.4 x 64.1 x 58.7 in, 90.6 in wheelbase), no badges."),
    ("Interior palette", "Charcoal walls, walnut cabinetry and desk, dark oak floor, graphite upholstery, brass pulls, warm 2700K-look lighting. No red or oxblood."),
    ("GitHub", "The repo cloned, but this session's GitHub link has no push access to arthckr88/22NFT. Everything was committed on branch render/full-3d-build locally and delivered as files here."),
]

COMPONENTS = [
    dict(name="Bluetti B4810 x2", where="Underbelly at the tail, between the spare tire and the hitch",
         why="Out of sight, frees cabin storage, weight on the higher-rated rear axle",
         dims="23.9 x 15.0 x 5.7 in each, side by side in a 52 x 18 x 7.5 in box", clear="12 in ground clearance (estimate)",
         weight="202 lb packs + about 25 lb box", service="Drop the box lid from below; disconnect at the box",
         risk="Departure angle 9.3 deg at the box vs 9.1 deg at the hitch; road spray; cold-weather self-heating needs incoming power (Bluetti to confirm)"),
    dict(name="Bluetti RV5 hub", where="Roadside desk pedestal, on the side wall", why="Directly above the batteries, keeps the kneehole open",
         dims="17.7 x 19.7 x 6.3 in", clear="Pedestal is 18 in wide x 24 in deep", weight="30.9 lb",
         service="Pedestal door; display faces into the cabinet", risk="Needs airflow: vent the pedestal toe-kick and back"),
    dict(name="Callsun 275W x6", where="Roof, 3 behind the AC and 3 ahead of it, crosswise", why="Six is the RV5's limit in parallel (41.1A of 50A per input)",
         dims="68.35 x 30.3 x 1.38 in each", clear="About 11.3 in each side to the roof edge; 2.5 in over vents",
         weight="29.8 lb each, 179 lb total", service="Walkable roof edges both sides", risk="Flat roof length is the open question; vents under panels"),
    dict(name="Roof combiner", where="Between the rear panel group and the AC", why="Shortest panel leads",
         dims="6.5 x 10 x 4 in modelled", clear="-", weight="In the 60 lb mounts/cable allowance", service="Lid on the roof", risk="Seal the roof entry gland"),
    dict(name="Victron Orion-Tr 12/48-8A x2", where="Under the passenger seat", why="Close to the starter battery; 48V carries the long run",
         dims="186 x 130 x 80 mm each", clear="-", weight="1.8 kg each", service="Seat base panel",
         risk="Wire the remote to ignition; fuse at the starter battery"),
    dict(name="Furrion Chill Cube 18K", where="Existing 14x14 opening, mid-roof", why="Variable speed, heat pump, keeps the ducted ceiling",
         dims="29.5 x 29 x 14.5 in", clear="Starlink and a walkway beside it", weight="72.4 lb", service="Shroud off on the roof",
         risk="Ducted air box has to meet East to West's duct runs"),
    dict(name="Starlink Mini", where="Roadside margin beside the AC", why="Lowest draw and smallest footprint", dims="11.4 x 9.8 x 1.4 in",
         clear="Clear sky view over the panels", weight="2.4 lb + mount", service="Bolt-down flat mount", risk="Cable entry shares the combiner gland"),
    dict(name="Splendide WDV2200XCD", where="Option A bath side, or option B rear garage", why="Vented: no tank water to dry",
         dims="23.5 W x 33.1 H x 22.6 D in", clear="Needs about 24 in of width", weight="148 lb", service="Front service; slide out on rails",
         risk="Vent hole in the wall; B needs bed-down clearance"),
    dict(name="Transfer switch", where="Under the curbside bench", why="Joins generator and shore before the RV5", dims="6 x 6 x 8 in modelled",
         clear="-", weight="small", service="Bench lid", risk="Confirm the coach's existing switch can be reused"),
]

LAUNDRY = [
    ("Space lost", "The drawer stack beside the bath (about 24 in of base storage)", "The curbside rear corner of the garage, about 24 x 24 in of floor"),
    ("Water run", "About 2 ft from the bath manifold", "About 13 ft from the bath manifold, under the floor"),
    ("Drain", "Short drop into the grey tank area", "About 8 ft to the grey tank; the washer's pump has to lift it"),
    ("Vent run", "About 1 ft through the roadside wall", "About 1 ft through the rear wall"),
    ("Weight position", "124 in from the rear wall: front axle +25 lb, rear +123 lb", "14 in from the rear wall: front axle -67 lb, rear +215 lb"),
    ("Noise near the desk", "About 7 ft from the desk chair", "About 2 ft from the desk chair"),
    ("Noise near the bed", "Away from the bed", "Directly under the lowered bed"),
    ("Counter", "Raised fold-and-charge counter fits on top", "No counter: the bed comes down above it"),
    ("Access", "Load from the aisle, any time", "Bed has to be up to load it"),
]

WALKTHROUGH = [
    ("Flat roof length", "From the cabover seam to the rear cap. The build needs about 233 in; the model assumes 234 in.", 1),
    ("14x14 AC opening position", "Distance from the rear wall. It decides how the panels split.", 1),
    ("Tail space and heights", "Ground to frame bottom at the tail, spare tire position, receiver height. The box needs about 52 x 18 x 7.5 in with its bottom at 12 in or higher.", 1),
    ("Rear axle weight", "Weigh the loaded coach per axle. The build adds 700-800 lb almost all on the rear axle (7,275 lb rated).", 2),
    ("Body width", "Outside and inside, at the roof and at the floor.", 2),
    ("Roof fixtures", "Positions and heights of the fans, skylight and antenna.", 2),
    ("Drawer stack width", "Bath side: the washer needs about 24 in.", 2),
    ("Lift bed lowered height", "Underside height above the floor when down; option B needs 34 in or more.", 2),
    ("Desk pedestal", "Inside width and depth for the RV5 (17.7 x 19.7 x 6.3 in).", 3),
    ("Ducted air box fit", "Photograph the stock ceiling assembly and duct openings for the Chill Cube box.", 3),
    ("Grey tank", "Location and inlet height, for both laundry drains.", 3),
    ("Generator and transfer switch", "Make, model, and where the existing transfer switch sits.", 3),
    ("Floor height", "Ground to the floor at the door.", 3),
    ("Alternator", "Single or dual 250A from the build sheet.", 3),
    ("Model year", "2026 or 2027.", 3),
]
