"""Source-grounded inputs. Geometry marked ESTIMATE is deliberately editable."""
import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
specs=[
dict(item='Alita 2027 22NF (dealer alias 22NFT)',dimension='26 ft L; 11 ft 5 in H; width TBD by OEM; 178 in wheelbase',weight='GVWR 11,000 lb; GCWR 13,500 lb; GAWR 4,630 front / 7,275 rear',status='Confirmed',source='https://www.easttowestrv.com/alita/22NF/15661',note='Published 2027 specification, not confirmation of Andrew’s selected VIN/year. Height includes roof equipment.'),
dict(item='Coach width / interior width',dimension='91 in exterior / 81 in interior',weight='Actual OCCC unknown',status='Credible',source='https://www.couchsrvnation.com/east-to-west/class-c-motorhome/alita/22nft1',note='Earlier dealer/dossier dimensions. Current OEM width is TBD; verify production unit.'),
dict(item='Floorplan / roof / spare area',dimension='Rear desk, lift bed, dry bath, cab-over bunk; usable roof 220 × 91 in; tail enclosure 45.5 × 37 × 9.5 in',weight='Factory generator and removed A/C weights unknown',status='ESTIMATE',source='https://www.easttowestrv.com/alita/22NF/15661',note='Floorplan relationships from OEM and handoff; every cabinet/window/roof fixture coordinate and underbody volume is reconstructed, not measured.'),
dict(item='Ford Transit chassis / body mounting',dimension='178 in WB; rear frame/body extension and spare coordinates VIN-dependent',weight='Use completed vehicle axle scales and door certification labels',status='Credible',source='https://madocumentupload.marketingassociates.com/api/Document/GetFile?v1=6853472&v2=021522100026&v3=60&v4=f71741fbb719e84d5ca63d295752152d1a09ad7d2d42658c23f9154a&v5=False',note='2022 Ford North America BEMM historical reference only. Current-year guide required. §5.14.5 ancillary subframe guidance explicitly excludes motorhomes.'),
dict(item='Bluetti RV5',dimension='17.72 × 19.69 × 6.30 in',weight='30.86 lb',status='Confirmed',source='https://www.bluettipower.com/products/rv5-b4810',note='120 V 5,000 W AC inverter. Published PV 12–50 V / 50 A / 1,800 W; independent input interpretation and BMS/AGS interface require manual confirmation. No outdoor rating assumed for hub.'),
dict(item='Bluetti B4810 ×2',dimension='Each 23.94 × 14.96 × 5.71 in',weight='Each 101.4 lb; pair 202.8 lb',status='Confirmed',source='https://www.bluettipower.com/blogs/buying-guide/guide-of-bluetti-rv5-48v-diy-solar-inverter-kit',note='51.2 V × 100 Ah = 5.12 kWh each, 10.24 kWh nominal total; published IP65 battery rating does not qualify complete tail assembly for road splash/submersion.'),
dict(item='Callsun 275 W bifacial ×6',dimension='Each 68.35 × 30.16 × 1.38 in',weight='Website lists 65.65 lb EACH; six 393.9 lb',status='Credible',source='https://callsunsolar.com/collections/partial-shade/products/275w-n-type-bifacial-solar-panel',note='Published mass is unusually high: use conservatively until net panel mass verified. Vmp 21.29 V / Imp 12.92 A; Voc 25.26 V / Isc 13.69 A; max series fuse 25 A. Six parallel: 77.52 A operating / 82.14 A short circuit. Nameplate 1,650 W.'),
dict(item='Victron Orion-Tr Smart ×2: provisional 12/48-8 (360 W)',dimension='Each 130 × 186 × 80 mm (5.12 × 7.32 × 3.15 in)',weight='Each 1.8 kg / 3.97 lb',status='Confirmed',source='https://www.victronenergy.com/media/pg/Orion-Tr_Smart_DC-DC_Charger_-_Isolated/en/specifications.html',note='Model choice ESTIMATE, family required by Andrew. Input 8–17 V; output 40–60 V; 360 W each at 40°C, 430 W at 25°C; 89% efficiency. Never connect 48 V output to RV5 50 V-max PV port. External B4810 charging requires explicit approval.'),
dict(item='Furrion Chill Cube 18K ducted heat pump',dimension='29.5 L × 29 W × 14.5 H in',weight='77.16 lb (not 85 lb shipping)',status='Confirmed',source='https://www.lippert.com/furrionchill-cube-variable-speed-rv-rooftop-air-conditionerr32with-heat-pump-18kbtu-black-ductedfacr18heda-bl-am-2025008215',note='FACR18HEDA-BL-AM / SKU 2025008215. AC-powered, not the earlier 48 V DC concept. Existing roof opening, duct/ADB/controller adaptation and bed obstruction must be checked against manuals.'),
dict(item='Splendide WDV2200XCD',dimension='23.5 W × 22.625 D × 33–33.375 H in; door-open depth ~40.5 in',weight='148 lb',status='Confirmed',source='https://www.splendide.com/downloads/WDV2200XCD_DataSheet.pdf',note='120 V / 11 A / 1,300 W max, dedicated 15 A circuit. 1 in front/back case clearance, 0 side minimum, ≥280 lb floor support. Door sweep is Credible diagram envelope; measure actual. 4 in metal exterior vent; enclosure door ≥8 sq in ventilation. Standpipe ≥1.25 in, 7 gpm; top 25–34 in above bottom, air break.'),
dict(item='Starlink Standard 4X (provisional variant)',dimension='594 × 383 × 39.7 mm (23.4 × 15.07 × 1.56 in)',weight='Antenna 6.4 lb; 8.3 lb with kickstand + 15 m cable; router 1.25 lb; PSU 1.43 lb',status='Confirmed',source='https://www.starlink.com/public-files/specification_sheet_standard.pdf',note='Variant/mount choice ESTIMATE. 75–100 W average, 110° field of view. Low fixed mount service/sky clearance not established.'),
dict(item='Factory onboard generator / AGS',dimension='Existing 4 kW generator; model/fuel/start connector unknown',weight='Existing mass included in base coach; no replacement mass added',status='ESTIMATE',source='https://www.easttowestrv.com/alita/22NF/15661',note='No assumption that RVMP 4000eM is installed. Dry-contact relay/start controller pending verified generator connector, safety interlocks and RV5 SOC interface.'),
dict(item='Tail enclosure, mounting and runs',dimension='45.5 × 37 × 9.5 in concept; 10.2 in minimum ground clearance; aggregate tail CG 70.8 in behind axle',weight='40 lb enclosure/mounting + 15 lb tail cable/protection allowance',status='ESTIMATE',source='https://www.fordpro.com/en-us/upfit/publications/',note='No steel attachment points, battery stacking, frame drilling, spare relocation, or departure clearance approved. Enclosure horizontal area intersects likely spare volume: rendered split/offset spare position must be measured.'),
dict(item='Generic flat-towed hatchback',dimension='12 ft × 5.4 ft × 4.9 ft visual envelope',weight='2,500 lb scenario only; actual Abarth year/curb/loading mass unknown',status='ESTIMATE',source='https://vehicleinfo.mopar.com/assets/publications/en-us/Fiat/2017/500/1973.pdf',note='No badges. 2017 factory manual permits manual-transmission flat towing in neutral up to 65 mph; exact selected year still unknown. Flat-tow permission, baseplate, towbar, hitch, brake and GCWR compatibility unresolved. At 11,000 lb coach weight only 2,500 lb GCWR margin remains.'),
]
decisions=[
'D01 Latest user instruction supersedes couch placement: RV5 and both B4810 packs are modeled at the tail, beneath the floor, beside a reconstructed spare. This increases rear axle load and unloading of the front axle; retain the decision while documenting feasibility gates.',
'D02 Six 275 W Callsun panels replace 1,200 W / six 200 W proposals. All six are parallel. Two provisional junction/protection boxes are represented. A split 3+3 input allocation is only a compatibility alternative, not a change to the requested six-parallel topology; electrical connection to independent RV5 inputs is NOT approved. One six-panel 77.52 A branch exceeds a published 50 A input.',
'D03 Current OEM 2027 22NF geometry uses 26 ft / 178 in WB. Exact production VIN/year is unknown. Earlier 22 ft 2 in / 156 in concept geometry was rejected because it conflicts with current manufacturer dimensions. 91 in width and 220 in usable roof remain estimates.',
'D04 Keep factory rear desk, drawers, kitchen, couch and lift bed. No under-desk laundry. A is adjacent to bath in a replaced storage bay; B is opposite desk on kitchen/fridge side of rear garage. Both are mutually exclusive modeled options; neither physical fit is verified.',
'D05 Select the ducted heat-pump Furrion FACR18HEDA-BL-AM to implement user selection. It is an AC appliance; earlier DC CountryMod concept is superseded. Factory removed A/C mass and duct adaptation remain unknown.',
'D06 Orion-Tr Smart 12/48-8 selected provisionally because Ford source is 12 V and house bus is 48 V. The current official table lists this model. Direct B4810 charge acceptance/BMS approval is unresolved; 48 V Orion output is incompatible with a 50 V-max RV5 PV input.',
'D07 Starlink Standard 4X used for visual dimensions because no variant was specified. Low mount, cable glands and sky view are estimated. No manufacturer logos or wordmarks appear in coach/appliance geometry.',
'D08 Saved personal style recovered: black #000, bone #f3f1ec, muted #e6e3dd, gold #cdb96a; Jost and IBM Plex Mono, editorial hairlines and small radii. Warm wood/charcoal materials implement Sunset Noir. Saved red status color deliberately excluded under latest instruction.',
'D09 All cabinet/window/fixture/chassis locations, roof edge/service clearances, spare position, enclosure and laundry plumbing paths are ESTIMATE. Renders are design visualization with actual component envelopes, not surveyed installation drawings.',
'D10 Callsun website mass 65.65 lb per panel used conservatively, not quietly replaced with a lighter plausible value. Unresolved net/shipping mass is a high-priority payload gate.',
'D11 AGS remains a generator requirement with solar → battery → generator priority. No stationary chassis engine auto-start. Diagram shows pending generator controller and RV5 SOC integration rather than asserting a working start interface.',
'D12 Prior +294 rear / −91 front represents approximately the 202.8 lb battery pair at an 80 in tail lever. It omits RV5, enclosure, brackets and wiring. Current model axle results use explicitly estimated longitudinal centers; actual axle scales govern.',
'D13 No complete 22NFT project room document was discoverable in accessible connected records. Maintain docs/PROJECT-22NFT.md as an explicit current project record with book links and walkthrough items; original inaccessible room remains an outstanding synchronization item.',
'D14 Pip bpy failed because workspace external DNS is blocked. Installed Blender 5.2.2 initially crashed during Metal detection on a headless machine. A local copied executable with a null-safe strstr interpose shim enabled native CPU Cycles. No installed app was modified. Scripts include portable fallback instructions.',

'D15 Render inspection exposed a reconstructed-frame interference in an early stacked tail study. Packs were changed to horizontal side-by-side in a 45.5 × 37 × 9.5 in enclosure envelope, beneath the rail. This is a modeling correction, not installation approval; bare-envelope margins remain too tight to establish cooling/service fit.',
'D16 Initial Cycles exterior showed boolean/bevel sidewall artifacts. Mesh normals and modifier application order were corrected and the image rerendered. Sky API renamed in Blender 5.2 was adapted; a failed viewer bundle was retried with a local Three.js alias. Direct image inspection tools timed out; local JPEG bytes were emitted successfully for visual review.',

'D17 Detailed washer case depth was corrected to 21.75 in with thin integrated front controls/door/handle inside the 22.625 in overall envelope; generic battery handles were recessed inside the published case envelope. Exported component envelopes are validated, while appliance detail shapes remain generic.',
'D18 Cable callouts were checked against modeled polylines: PV home run rounded to 5.9 m, Orion aft route 5.6 m, generator AC 5.0 m. These are approximate model paths, not purchase lengths; add verified actual routing, glands and service loops.',
'D19 Laundry B is shown with the movable editing chair cleared from the rear bay for loading. This is a render staging condition, not a verified chair parking/storage solution or simultaneous editing/laundry access. Bed remains raised and lowered swept volume unresolved.',
'D20 Reconstructed lining/clear cabin width is about 84 in; an earlier dealer/dossier value was 81 in. Neither confirms this selected production unit. All cabinetry/bay coordinates stay ESTIMATE; measure actual clear width before any fit decision.',

'D21 Tail case geometry uses a thin formed shell/lid inside the nominal 45.5 × 37 × 9.5 in envelope, with connected proposed carrier channels and formed mounting angles. Construction material, gauge, fasteners, mounting permission and actual mass are unverified. 40 lb remains an ESTIMATE allowance, not a CAD mass calculation.',
'D22 Inner rear dual tires are represented provisionally for the 11,000 lb current-reference Transit cutaway. This is generic chassis geometry, not a verified production-unit tire/wheel or suspension specification. Confirm exact chassis designation and running gear at VIN walkthrough.',
'D23 Browser automation failed through localhost (EPERM), direct debugging pipe and a lighter single-process retry. Use a native CoreText/CoreGraphics PDF authoring fallback. The actual GLTFLoader, embedded gzip model, shared layer behavior, exported envelopes and axle conservation are validated in Node; live browser appearance and interaction remain unverified in this workspace.',
'D24 Native PDF verification compilation initially failed at an unwritable system Swift module cache. A workspace-local module cache resolved it. All retries and visual render corrections are recorded in QA.md; no approval or user input was requested.',
'D25 Large full-resolution PNG transfers exceeded execution-tool output limits and truncated their JSON payloads. Retried with small byte-range chunks and verified file lengths before upload. Original local render quality and dimensions were retained.',
]
if __name__=='__main__':
 (ROOT/'docs/specs.json').write_text(json.dumps(specs,indent=2))
 (ROOT/'docs/SPECS.md').write_text('# Source-grounded specification register\n\nResearch snapshot: 2026-10-07. Confirmed means a published specification for that named variant, not confirmed fit to a selected VIN. Credible means a dealer/secondary or unresolved published measurement. ESTIMATE means reconstructed geometry or a modeling assumption.\n\n| Item | Dimensions / weight | Status | Source / qualification |\n|---|---|---|---|\n'+'\n'.join(f'| {s["item"]} | {s["dimension"]}; {s["weight"]} | {s["status"]} | [Source]({s["source"]}). {s["note"]} |' for s in specs))
 (ROOT/'docs/DECISIONS.md').write_text('# DECISIONS\n\n'+'\n\n'.join(decisions))
